#!/python3
# -*- coding: utf-8 -*-


def gcd(a, b):
    return a if b == 0 else gcd(b, a % b)


class Fraction:
    def __init__(self, numerator, denominator):
        g = gcd(numerator, denominator)
        self.top = int(numerator / g)
        self.bottom = int(denominator / g)

    def __eq__(self, other):
        first_num = self.top * other.bottom
        second_num = other.top * self.bottom
        return first_num == second_num

    def __add__(self, other):
        return Fraction(
            self.top * other.bottom + other.top * self.bottom,
            self.bottom * other.bottom
        )

    def __str__(self):
        return "{}/{}".format(self.top, self.bottom)


if __name__ == "__main__":
    fraction1 = Fraction(4, 5)
    print(fraction1 + Fraction(1, 8)) # => 37/40
    print(Fraction(40, 70)) # => 4/7
    print(Fraction(1, 6) + Fraction(1, 3)) # => 1/2
